// 用户信息相关type
export const GET_USER_AUTH_LIST = 'GET_USER_AUTH_LIST';
export const GET_USER_AUTH_LIST_SUCCESS = 'GET_USER_AUTH_LIST_SUCCESS';
export const GET_USER_AUTH_LIST_REQUEST = 'GET_USER_AUTH_LIST_REQUEST';
export const GET_USER_AUTH_LIST_FAILURE = 'GET_USER_AUTH_LIST_FAILURE';
